// Short functional notes for structures in the 3D labs (tap-to-name and spotter feedback).
// Each entry: [RegExp on the mesh name, text]. First match wins, so specific patterns come first.
export const GROUP_NAMES = {
  skin: 'Skin & surface', auricle: 'Auricle (pinna)', bone: 'Bones', tbone: 'Temporal bone', teeth: 'Teeth', tongue: 'Tongue', tonguem: 'Tongue muscles',
  lips: 'Lips (orbicularis oris)', palate: 'Soft palate & uvula', airway: 'Airway & pharynx', constrictor: 'Pharyngeal constrictors', larynx: 'Larynx', oesophagus: 'Oesophagus',
  nerve: 'Cranial nerves', cn: 'Cranial nerves', vnerve: 'Vestibulocochlear nerve', brainstem: 'Brainstem', nucleus: 'Brainstem nuclei', vnuc: 'Vestibular & ocular nuclei',
  cortex: 'Cerebral cortex', cortexL: 'Left hemisphere', cortexR: 'Right hemisphere', auditoryCortex: 'Auditory cortex', acortex: 'Auditory cortex', cerebellum: 'Cerebellum',
  deep: 'Deep grey matter', thalamus: 'Thalamus', limbic: 'Limbic structures', ventricle: 'Ventricles', artery: 'Cerebral arteries', vessel: 'Blood vessels',
  ossicle: 'Ossicles', tm: 'Tympanic membrane', labyrinth: 'Inner ear', tube: 'Eustachian tube', eye: 'Eyeballs', eyemuscle: 'Extra-ocular muscles', trig: 'Trigeminal nerve',
  superficial: 'Platysma & SCM', strap: 'Infrahyoid (strap) muscles', suprahyoid: 'Suprahyoid muscles', cartilage: 'Laryngeal cartilages', hyoid: 'Hyoid bone',
  membrane: 'Laryngeal membranes', intrinsic: 'Intrinsic laryngeal muscles', pharynx: 'Pharynx, trachea & oesophagus', gland: 'Glands',
  facial: 'Muscles of facial expression', mastication: 'Muscles of mastication', tmj: 'Temporomandibular joint', floor: 'Floor of mouth', muscle: 'Muscles',
};

const INFO = [
  // larynx
  [/Posterior crico-arytenoid/, 'The only abductor of the vocal folds: rotates the arytenoids to open the glottis for breathing. Supplied by the recurrent laryngeal nerve (X). Bilateral paralysis → stridor, airway risk.'],
  [/Lateral crico-arytenoid/, 'Adducts the vocal processes and closes the membranous glottis. Recurrent laryngeal nerve.'],
  [/Transverse arytenoid|oblique arytenoid/, 'Interarytenoid muscles: slide the arytenoids together to close the posterior (cartilaginous) glottis. The ary-epiglottic part helps close the laryngeal inlet during swallowing.'],
  [/thyro-arytenoid|Thyro-epiglottic/, 'Thyroarytenoid (with vocalis) forms the body of the vocal fold: shortens and thickens the fold, lowers pitch, adducts. Thyro-epiglottic fibres help close the inlet.'],
  [/cricothyroid muscle/, 'Tilts the thyroid on the cricoid to lengthen and tense the vocal folds, raising pitch. Only intrinsic muscle supplied by the external branch of the superior laryngeal nerve.'],
  [/Thyroid cartilage/, 'Largest laryngeal cartilage (Adam\'s apple). Shields the vocal folds; the folds attach inside its angle. Moves with the hyoid in hyolaryngeal elevation.'],
  [/Cricoid cartilage/, 'Complete signet-ring cartilage at C6: foundation of the larynx and upper limit of the trachea. The cricopharyngeus (UES) attaches to it.'],
  [/Arytenoid cartilage/, 'Pyramid-shaped cartilages on the cricoid: the vocal ligament attaches to the vocal process. Their rocking and gliding open and close the glottis.'],
  [/Corniculate|Cuneiform cartilage/, 'Small cartilages in the aryepiglottic folds that support the posterior laryngeal inlet.'],
  [/Epiglottis/, 'Leaf-shaped elastic cartilage that folds back over the laryngeal inlet during the swallow, deflecting the bolus to the pyriform sinuses.'],
  [/Quadrangular membrane/, 'Forms the aryepiglottic folds above and the false (vestibular) folds below.'],
  [/cricothyroid ligament/, 'Connects cricoid and thyroid; upward continuation forms the conus elasticus and vocal ligament. Site of emergency cricothyrotomy.'],
  [/thyrohyoid ligament|Thyrohyoid membrane/, 'Suspends the larynx from the hyoid. Pierced by the internal branch of the superior laryngeal nerve (sensation above the folds; the cough-trigger area).'],
  [/Cricopharyngeal ligament/, 'Anchors the lower pharynx to the cricoid lamina.'],
  [/Hyoid bone/, 'Floating U-shaped bone anchoring tongue and larynx. Its anterior–superior excursion in the swallow opens the UES and protects the airway.'],
  [/Thyrohyoid muscle/, 'Approximates thyroid cartilage and hyoid; with the hyoid fixed it elevates the larynx. Supplied by C1 via XII.'],
  [/Sternohyoid|Sternothyroid|Omohyoid/, 'Infrahyoid (strap) muscles: depress the hyoid and larynx after the swallow and in low-pitched singing. Ansa cervicalis (C1–C3).'],
  [/digastric/, 'Anterior belly (V3) and posterior belly (VII) meet at an intermediate tendon: elevates the hyoid, opens the jaw.'],
  [/Mylohyoid/, 'Muscular floor of the mouth: raises the floor and tongue at the start of the swallow. Nerve to mylohyoid (V3).'],
  [/Geniohyoid/, 'Pulls the hyoid forward: the main driver of anterior hyolaryngeal excursion that opens the UES. C1 via XII. A target of Shaker and chin-tuck-against-resistance exercises.'],
  [/Stylohyoid/, 'Draws the hyoid up and back during swallowing. Facial nerve (VII).'],
  [/Platysma/, 'Thin superficial neck muscle: tenses the neck skin, depresses the mandible and lip corners. Facial nerve.'],
  [/Sternocleidomastoid/, 'Rotates the head to the opposite side and flexes the neck; accessory nerve (XI). Landmark for the carotid sheath.'],
  [/parathyroid/, 'Regulate calcium; at risk during thyroid surgery (as is the recurrent laryngeal nerve).'],
  // pharynx, palate, oral
  [/Superior pharyngeal constrictor/, 'Forms Passavant\'s ridge with the velum for velopharyngeal closure; begins the pharyngeal squeeze. Pharyngeal plexus (X).'],
  [/Middle pharyngeal constrictor/, 'Arises from the hyoid; propels the bolus down the pharynx.'],
  [/Inferior pharyngeal constrictor/, 'Thyropharyngeus squeezes the bolus; its lowest part, cricopharyngeus, is the upper oesophageal sphincter (UES), tonically closed at rest.'],
  [/Stylopharyngeus/, 'Elevates and widens the pharynx during the swallow; the only muscle supplied by the glossopharyngeal nerve (IX).'],
  [/Palatopharyngeus/, 'Forms the posterior faucial pillar; elevates the pharynx and narrows the oropharyngeal isthmus.'],
  [/Soft palate/, 'Velum: elevates against the posterior pharyngeal wall for oral sounds and to seal the nasopharynx in swallowing. Velopharyngeal inadequacy → hypernasality, nasal emission, nasal regurgitation.'],
  [/Uvula of palate/, 'Midline projection of the velum (musculus uvulae adds bulk to velar closure). A bifid uvula can signal submucous cleft palate.'],
  [/Palatine tonsil/, 'Lymphoid tissue between the faucial pillars; enlargement can affect resonance and swallowing.'],
  [/Nasopharynx/, 'Airway behind the nose above the velum; contains the Eustachian tube openings and adenoids.'],
  [/Oropharynx/, 'From the velum to the tip of the epiglottis; contains the valleculae (a common residue site).'],
  [/Laryngopharynx/, 'Hypopharynx: from the epiglottis to the cricoid, with the pyriform sinuses on either side of the larynx.'],
  [/Mucosa of nasal cavity/, 'Nasal cavity lining; a resonator for nasal sounds and the path of nasal airflow.'],
  [/Trachea/, 'Windpipe from C6 to the carina; C-shaped cartilages keep it open. Site of tracheostomy and, after laryngectomy, the stoma.'],
  [/Oesophagus/, 'Muscular tube from the UES to the stomach; peristalsis takes 8–20 s. Upper third striated, lower two-thirds smooth muscle.'],
  [/^Tongue$/, 'Main articulator and bolus propeller: intrinsic muscles shape it, extrinsic muscles move it. Hypoglossal nerve (XII); taste via VII (anterior 2/3) and IX (posterior 1/3).'],
  [/Genioglossus/, 'Protrudes and depresses the tongue; keeps the airway open in sleep. Unilateral XII lesion → tongue deviates to the weak side.'],
  [/Hyoglossus/, 'Retracts and depresses the tongue sides. Hypoglossal nerve (XII).'],
  [/Orbicularis oris/, 'Sphincter of the lips: rounding and closure for /p b m w/ and the oral seal that stops anterior spillage.'],
  [/Buccinator/, 'Cheek muscle: keeps the bolus between the teeth and prevents pocketing in the buccal sulcus. Facial nerve.'],
  [/Zygomaticus|Risorius|Levator labii|Levator anguli|Depressor anguli|Mentalis/, 'Muscle of facial expression acting on the lips and mouth corners (spreading, smiling, lowering). Facial nerve (VII); an UMN lesion spares the forehead.'],
  [/masseter|Masseter/, 'Powerful jaw elevator for chewing. Mandibular nerve (V3).'],
  [/Temporalis/, 'Elevates and retracts the mandible. Mandibular nerve (V3).'],
  [/Medial pterygoid/, 'Elevates the mandible and moves it side to side. V3.'],
  [/lateral pterygoid/, 'Protrudes and opens the jaw, pulling the TMJ disc forward. V3.'],
  [/temporomandibular/, 'Temporomandibular joint: hinge and glide movements for jaw opening; TMJ disorders can cause pain, clicking and somatic tinnitus.'],
  [/Parotid duct/, 'Stensen\'s duct: carries parotid saliva to the cheek opposite the upper second molar.'],
  [/Parotid gland/, 'Largest salivary gland (serous saliva, IX via the otic ganglion). The facial nerve branches run through it.'],
  [/Submandibular gland/, 'Produces most resting saliva (VII via chorda tympani). Reduced after radiotherapy → xerostomia.'],
  [/Sublingual gland/, 'Mucous saliva into the floor of the mouth (VII).'],
  [/incisor|canine|premolar|molar/, 'Teeth: the upper incisors are the articulatory contact for labiodental /f v/ and dental sounds; molars grind the bolus.'],
  [/^Mandible$/, 'Lower jaw: opens and closes to set the oral opening for vowels and consonants; houses the lower teeth.'],
  [/Maxilla/, 'Upper jaw and anterior hard palate (alveolar ridge): the target for alveolar and palatal consonants. Clefts arise from failed fusion here.'],
  [/Palatine bone/, 'Posterior part of the hard palate; the velum attaches to its edge.'],
  // nerves
  [/Recurrent laryngeal/, 'Branch of X that loops under the aorta (left) or subclavian artery (right): supplies all intrinsic muscles except cricothyroid and sensation below the folds. Injury → vocal fold paralysis, breathy voice.'],
  [/Superior laryngeal/, 'Branch of X: internal branch = sensation above the folds; external branch = cricothyroid (pitch).'],
  [/Vagus nerve/, 'CN X: pharynx, larynx and soft palate motor (nucleus ambiguus), laryngeal sensation, parasympathetic to the viscera. Lesions → dysphonia, dysphagia, hypernasality.'],
  [/Glossopharyngeal/, 'CN IX: pharyngeal sensation (gag afferent), taste of the posterior tongue, stylopharyngeus, parotid secretion.'],
  [/Hypoglossal nerve/, 'CN XII: all tongue muscles except palatoglossus. LMN lesion → atrophy, fasciculations, deviation to the weak side.'],
  [/Accessory nerve/, 'CN XI: sternocleidomastoid and trapezius.'],
  [/Facial nerve/, 'CN VII: facial expression, stapedius, taste (anterior 2/3), submandibular and sublingual glands. Runs through the temporal bone next to the middle ear.'],
  [/Chorda tympani/, 'Branch of VII crossing the middle ear behind the eardrum: taste to the anterior tongue and secretomotor fibres to the submandibular/sublingual glands. At risk in ear surgery.'],
  [/Trigeminal nerve/, 'CN V: facial sensation, muscles of mastication (V3), tensor tympani and tensor veli palatini. Its input to the DCN underlies somatic tinnitus.'],
  [/mandibular nerve|Inferior alveolar|Lingual nerve|Nerve to mylohyoid/, 'Branch of the mandibular nerve (V3): sensation of the lower teeth, tongue (lingual) and motor to mylohyoid / anterior digastric.'],
  [/Maxillary nerve/, 'V2: sensation of the upper teeth, palate and mid-face.'],
  [/Vestibulocochlear|Cochlear nerve/, 'CN VIII: cochlear division carries hearing to the cochlear nuclei; vestibular division carries balance to the vestibular nuclei. Vestibular schwannoma arises on it.'],
  [/Vestibular nerve/, 'Carries canal and otolith signals to the vestibular nuclei; inflamed in vestibular neuritis.'],
  [/Olfactory nerve/, 'CN I: smell (contributes to flavour).'],
  [/Optic nerve/, 'CN II: vision.'],
  [/Oculomotor nerve/, 'CN III: most eye muscles (incl. medial rectus in the VOR), eyelid elevation, pupil constriction.'],
  [/Trochlear nerve/, 'CN IV: superior oblique.'],
  [/Abducens nerve/, 'CN VI: lateral rectus (abduction) — the first motor link of the horizontal VOR.'],
  // ear
  [/Helix|Antihelix|Tragus|concha|Lobule of auricle|Scapha|Triangular fossa|Crura|auricle|Cymba|Intertragic|notch|tubercle/i, 'Part of the auricle: collects sound and adds direction-dependent spectral cues; the concha resonates near 5 kHz.'],
  [/Tympanic membrane/, 'Eardrum: converts sound pressure into ossicle vibration; its area ratio to the oval window gives most of the middle-ear pressure gain.'],
  [/Malleus/, 'Hammer: attached to the eardrum; transfers vibration to the incus.'],
  [/Incus/, 'Anvil: lever between malleus and stapes; its long process is the site of ossicular erosion and of middle-ear implant couplers.'],
  [/Stapes/, 'Stirrup: its footplate in the oval window drives the cochlear fluids. Fixed in otosclerosis. Stapedius (VII) damps it in the acoustic reflex.'],
  [/Cochlea/, 'Hearing organ: 2¾ turns; the basilar membrane is tuned from high frequencies at the base to low at the apex.'],
  [/Vestibule/, 'Contains the utricle and saccule and joins the semicircular canals: balance sensors for gravity, linear and angular acceleration.'],
  [/Auditory tube/, 'Eustachian tube: equalises middle-ear pressure; opened by tensor veli palatini during swallowing and yawning. Dysfunction → otitis media with effusion.'],
  [/Temporal bone/, 'Houses the middle and inner ear, the facial nerve canal and the internal acoustic meatus.'],
  [/Sigmoid sinus/, 'Venous sinus behind the mastoid draining to the jugular bulb; a cause of pulsatile tinnitus when dehiscent.'],
  [/Internal jugular/, 'Main venous drainage of the brain; a high jugular bulb sits below the middle ear.'],
  [/Internal carotid/, 'Supplies most of the cerebral hemisphere via the MCA and ACA; runs close to the cochlea in the petrous bone.'],
  [/External carotid|Facial artery|Maxillary artery|Superficial temporal|Superior thyroid/, 'Branch of the external carotid system supplying the face, jaws, tongue or neck.'],
  [/carotid artery/, 'Common carotid: divides at C4 into internal (brain) and external (face and neck) carotids.'],
  [/jugular vein/, 'Venous drainage of the head and neck.'],
  // brain
  [/Opercular part of inferior frontal|Triangular part of inferior frontal/, 'Broca\'s area (left): speech planning, syntax and phonological working memory. Lesion → non-fluent aphasia; with insula → apraxia of speech.'],
  [/Orbital part of +inferior frontal|Orbital gyri/, 'Orbitofrontal cortex: semantic control, social behaviour and reward (vmPFC gating in tinnitus).'],
  [/Precentral gyrus/, 'Primary motor cortex: face and tongue represented low on the gyrus (bilateral corticobulbar output to cranial nerve nuclei).'],
  [/Postcentral gyrus/, 'Primary somatosensory cortex: oral sensation feeds speech and swallowing control.'],
  [/Superior temporal gyrus|Temporal plane/, 'Auditory association cortex; the posterior part (planum temporale, Wernicke\'s area) maps sound to meaning. Lesion → fluent aphasia with poor comprehension.'],
  [/Transverse temporal gyri/, 'Heschl\'s gyrus: primary auditory cortex, tonotopic (low anterolateral, high posteromedial).'],
  [/Supramarginal/, 'Supramarginal gyrus: phonological processing and somatosensory feedback for speech; lesion (with arcuate) → conduction aphasia.'],
  [/Angular gyrus/, 'Reading, writing and calculation; lesion → alexia with agraphia, Gerstmann signs.'],
  [/Middle temporal|Inferior temporal|Temporal pole|occipitotemporal/, 'Ventral stream: word meaning and naming (anterior temporal lobe atrophy → semantic PPA).'],
  [/Superior frontal|Middle frontal|frontal sulcus/, 'Prefrontal cortex: executive function, working memory, attention (impaired after TBI and in bvFTD).'],
  [/Insula/, 'Insula: motor speech planning (AOS), swallowing, taste and interoception; part of the salience / distress network.'],
  [/Superior parietal|Intraparietal|Precuneus/, 'Parietal cortex: spatial attention and the default-mode network (right-sided lesions → neglect).'],
  [/occipit|Cuneus|Lingual gyrus|Calcarine/i, 'Visual cortex and visual association areas.'],
  [/sulcus/, 'A sulcus: a groove separating gyri; landmarks for localising lesions.'],
  [/Caudate/, 'Caudate nucleus (basal ganglia): action selection, cognition; degenerates in Huntington\'s disease.'],
  [/Putamen/, 'Putamen (basal ganglia): motor loop for scaling speech movements; dopamine loss here → hypokinetic dysarthria in Parkinson\'s.'],
  [/Globus pallidus/, 'Globus pallidus: main output of the basal ganglia to the thalamus.'],
  [/Thalamus/, 'Thalamus: relay to the cortex (MGB for hearing); thalamic lesions can cause aphasia and attention deficits.'],
  [/Hippocampus/, 'Hippocampus: forming new memories; early atrophy in Alzheimer\'s disease.'],
  [/Hypothalamus/, 'Hypothalamus: autonomic and hormonal control (stress response).'],
  [/Red nucleus/, 'Red nucleus: cerebellar–motor relay in the midbrain.'],
  [/Corpus callosum/, 'Corpus callosum: links the two hemispheres.'],
  [/ventricle|Choroid plexus/i, 'CSF-filled ventricles; enlargement (hydrocephalus) affects gait, cognition and continence.'],
  [/Medulla oblongata/, 'Medulla: swallowing central pattern generator (NTS, nucleus ambiguus), IX–XII nuclei. Lateral medullary (Wallenberg) stroke → severe dysphagia.'],
  [/Pons/, 'Pons: V and VII motor nuclei, VI nucleus, cochlear nuclei nearby; relays cortex to cerebellum.'],
  [/Midbrain/, 'Midbrain: III and IV nuclei, inferior colliculus (hearing), substantia nigra.'],
  [/Pyramid of medulla/, 'Pyramids: corticospinal tracts before they cross.'],
  [/cerebellar peduncle/, 'Cerebellar peduncle: carries cerebellar output (ataxic dysarthria if damaged).'],
  [/Flocculus|Nodule of vermis/, 'Vestibulocerebellum: adapts the VOR and gaze; lesions → nystagmus, imbalance.'],
  [/lobule|vermis|Lingula|Central lobule|Tonsil of cerebellum|Pyramis|Folium/, 'Cerebellum: timing and coordination of speech and limb movements. Lesion → ataxic dysarthria (scanning speech, irregular DDK).'],
  [/Nucleus ambiguus/, 'Nucleus ambiguus: motor neurons for pharynx, larynx and palate (IX, X).'],
  [/Nucleus of solitary tract/, 'NTS: receives taste and pharyngeal sensation; key part of the swallowing central pattern generator.'],
  [/Nucleus of hypoglossal/, 'Hypoglossal nucleus: tongue motor neurons.'],
  [/Motor nucleus of facial/, 'Facial motor nucleus: lip and facial muscles.'],
  [/nucleus of vagus/, 'Dorsal motor nucleus of X: parasympathetic output to the viscera.'],
  [/cochlear nucleus/, 'Cochlear nucleus: first auditory relay; the dorsal part (DCN) integrates sound and somatosensation (tinnitus).'],
  [/Inferior colliculus/, 'Inferior colliculus: obligatory midbrain auditory relay; hyperactive in tinnitus models.'],
  [/Medial geniculate/, 'Medial geniculate body: auditory thalamus projecting to Heschl\'s gyrus.'],
  [/Superior colliculus/, 'Superior colliculus: visual orienting and eye movements.'],
  [/Vestibular nuclei/, 'Vestibular nuclei: integrate canal, otolith, visual and neck input; drive VOR and posture.'],
  [/abducens nerve\b|Nucleus of abducens/, 'Abducens nucleus: lateral rectus motor neurons plus internuclear neurons to the opposite III via the MLF (horizontal gaze).'],
  [/Nucleus of oculomotor|trochlear nerve$/, 'Oculomotor / trochlear nucleus: eye movement motor neurons.'],
  [/Middle cerebral/, 'Middle cerebral artery: supplies Broca\'s, Wernicke\'s, motor and auditory cortex. MCA stroke is the commonest cause of aphasia and neurogenic dysphagia.'],
  [/Anterior cerebral/, 'Anterior cerebral artery: medial frontal lobe and SMA (transcortical motor aphasia, leg weakness).'],
  [/Posterior cerebral/, 'Posterior cerebral artery: occipital lobe, thalamus, hippocampus (alexia without agraphia, memory).'],
  [/communicating artery/, 'Part of the circle of Willis: collateral flow between the carotid and vertebrobasilar systems.'],
  [/Basilar artery|Vertebral artery/, 'Vertebrobasilar system: brainstem, cerebellum and inner ear (AICA/labyrinthine artery). Occlusion → vertigo, dysarthria, dysphagia.'],
  // eyes / misc
  [/rectus|oblique muscle/, 'Extra-ocular muscle moving the eye; the VOR drives recti in pairs.'],
  [/Sclera|Cornea|Iris|Lens/, 'Part of the eyeball.'],
  [/region|Eyebrow|Philtrum|sulcus of|commissure|Angle of mouth|triangle/i, 'Surface region of the head and neck.'],
  [/Frontal bone|Parietal bone|Occipital bone|Sphenoid|Ethmoid|Vomer|Zygomatic bone|Nasal bone/, 'Bone of the skull.'],
  [/Vertebra|Atlas|Axis/, 'Cervical vertebra: a landmark for pharyngeal and laryngeal levels (hyoid ≈ C3, thyroid ≈ C4–5, cricoid ≈ C6).'],
  [/Clavicle|sternum/, 'Anchor for neck muscles.'],
];

export function infoFor(name) {
  for (const [re, t] of INFO) if (re.test(name)) return t;
  return '';
}
export function pretty(name) {
  return String(name).replace(/\.r$/, ' (right)').replace(/\.l$/, ' (left)').replace(/\*/g, '').replace(/\s+/g, ' ').trim();
}
export const baseName = (name) => String(name).replace(/\.(r|l)$/, '').replace(/ \((left|right)\)$/, '').replace(/\*/g, '').replace(/\s+/g, ' ').trim();
